#!/usr/bin/env python3
"""
Quick Direla ID test script.

Purpose:
- Seed a small number of multi-party transaction groups that all share a
  common Direla (universal) ID per group.
- Let you verify that:
  - `/direla/ids` returns those IDs
  - The Operator Console shows them under "Existing Direla IDs"
  - Downstream matching / confidence flows behave as expected.
"""

import sys
import os
from typing import List

from decimal import Decimal

# Ensure local imports work when running as a script
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from shared.database import SessionLocal  # type: ignore
from shared.models import Transaction  # type: ignore
from seed_transactions import TransactionSeeder, ScenarioType  # type: ignore


def _persist_group(db, group) -> None:
  """Persist a TransactionGroup generated by TransactionSeeder."""
  assert group.direla_id, "TransactionGroup is missing a Direla ID"

  print(
    f"- Seeding Direla ID {group.direla_id} "
    f"({group.scenario_type.value}) with {len(group.transactions)} transactions"
  )

  for txn in group.transactions:
    if not isinstance(txn, Transaction):
      raise TypeError("Expected Transaction instance in group.transactions")
    db.add(txn)


def seed_direla_test_flows(clear_existing: bool = False) -> None:
  """
  Seed a handful of Direla test flows.

  This intentionally keeps the volume low so you can quickly see
  the effect in the Operator Console and `/direla/ids` endpoint.
  """
  db = SessionLocal()

  try:
    seeder = TransactionSeeder(db)

    if clear_existing:
      print("⚠️  Clearing existing transactions table before seeding Direla tests...")
      db.query(Transaction).delete()
      db.commit()

    print("🚀 Seeding Direla test flows...\n")

    # 1) Perfect 3‑party airtime flow (should be high confidence)
    airtime_group = seeder.generate_perfect_airtime_match()
    _persist_group(db, airtime_group)

    # 2) Perfect electricity flow
    electricity_group = seeder.generate_perfect_electricity_match()
    _persist_group(db, electricity_group)

    # 3) Timing discrepancy group (should lean toward manual review)
    timing_group = seeder.generate_timing_discrepancy()
    _persist_group(db, timing_group)

    # 4) Amount discrepancy group
    amount_group = seeder.generate_amount_discrepancy()
    _persist_group(db, amount_group)

    db.commit()

    print("\n✅ Direla test flows seeded.")
    print("You can now:")
    print("  - Hit `/direla/ids` via the BFF")
    print("  - Open the Operator Console and check 'Existing Direla IDs'")
    print("Each row should correspond to one of the seeded Direla IDs above.")

  except Exception as e:
    db.rollback()
    raise
  finally:
    db.close()


if __name__ == "__main__":
  """
  Usage:
    python backend/test_direla_ids.py
    python backend/test_direla_ids.py --clear
  """
  clear = "--clear" in sys.argv
  seed_direla_test_flows(clear_existing=clear)

